### ISSUE TITLE
build runner doesn't produce any translation key/values

### ISSUE THREAD

**Issue by JohnnyRainbow81** [DieGlueckswurst/localize_it#1]
Hi! 
Thank you for your very interesting approach to unfuck the insane & unneccessarily complicated normal way of doing plain localizations in flutter 😆
 
Unfortunately it doesn't seem to work for me. 
My approach so far:
1) I added all dependencies you mentioned in your pub.dev plus the dependency for Get
2) I installed the vscode plugin
3) I ran localize_it:Create
4) I c/p'd my DeepL-Key
5) I entered a test-String to main.dart into the example app, like "Hello world".tr
6) I called flutter pub run build_runner build --delete-conflicting-outputs
7) Nothing was created: 

💡    Missing Localizations: 0
💡    New Localizations:     0

✅    Done!

Did I miss something?

**Comment by DieGlueckswurst** [comment]
Hi Johnny! Don't forget to run `flutter clean` before running the `build`method :)

**Comment by JohnnyRainbow81** [comment]
I also tried that. Unfortunately it didn't help...

**Comment by DieGlueckswurst** [comment]
just to be extra clear. In step 5 you said, you your string is "Hello world".tr. For the package to work, all your  Strings need to have *single-quotes*.

**Comment by DieGlueckswurst** [comment]
can you also show your `config_file`? (**without the DeepL-Key**)

**Comment by JohnnyRainbow81** [comment]
That was it! Haha, oh man... I generally use double-quotes, so I guess there will be many other people stumbling over this when your library gains more traction... :)

**Comment by JohnnyRainbow81** [comment]
Thanks! Seems to work fine now 👍

**Comment by DieGlueckswurst** [comment]
oh wow :D ok good to know! I assumed single-quotes since that's Flutters way to go: https://dart-lang.github.io/linter/lints/prefer_single_quotes.html

I could add an option to the `config` file like `useDoubleQuotes = false`. What do you think? Would that make things more clear?

**Comment by JohnnyRainbow81** [comment]
Would it be more complicated to support both without the necessity to configure it?

**Comment by JohnnyRainbow81** [comment]
Otherwise yes, to have an option like this would be a good start

**Comment by DieGlueckswurst** [comment]
added this feature in the latest [version 1.1.1](https://pub.dev/packages/localize_it).
